# Site settings
title: Jeff Johannsen Data Science Portfolio
description: A place to check out my projects and get ahold of me.

# User settings
username: Jeff Johannsen
user_description: I'm a Data Scientist with a background in Supply Chain Operations, Process Improvement, and Finance. My favorite part of Data Science is being able to communicate complex problems through data visualizations. Outside of Data Science, I'm a polymath with a wide range of interests. My current side projects include tourism industry data collection for a mobile app and AI Safety research. I'm constantly focusing on self-improvement. My current learning goals include mindfulness and new Python packages for data science!
user_title: Data Science | Data Analysis | Machine Learning
email: jeffjohannsen@gmail.com
github_username:  jeffjohannsen

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
